// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day01.Models;

[Index("Dept_Id", Name = "IX_Courses_Dept_Id")]
public partial class Course
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    public int Degree { get; set; }

    public int MinDegree { get; set; }

    public int Dept_Id { get; set; }
}